### PR TITLE
fix golint

### PR DESCRIPTION
**Pull request by ZP-AlwaysWin**
/kind cleanup

Fix golint failure in pkg/printers/jsonpath.go

### CODE REVIEW

**Comment by ZP-AlwaysWin** [comment]
/assign @juanvallejo
PTAL 😄

**Comment by nikhita** [comment]
@ZP-AlwaysWin the code here is just the copy of the code in https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/cli-runtime. To fix this, you'll need to fix it in the latter. :)

/close

**Pull request closed without merging**
